# Generated by Django 6.0.1 on 2026-01-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollnumber', models.IntegerField()),
                ('email', models.TextField(default='')),
                ('phonenumber', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('set_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_password', to='Track.register')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_user', to='Track.register')),
            ],
        ),
    ]
