# Generated by Django 6.0.1 on 2026-01-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='login',
            name='set_password',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phonenumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='rollnumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='set_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
