# Generated by Django 6.0.1 on 2026-01-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_rename_user_id_login_user_remove_login_set_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user',
            new_name='user_id',
        ),
    ]
